name: Auto-rebase Codex PR

on:
  pull_request_target:
    types: [opened, synchronize, labeled]   # реагируем на любые обновления PR
    branches: [main]

jobs:
  rebase:
    # 1) ветка-источник начинается с "codex/"
    # 2) или у PR есть лейбл "codex"
    if: startsWith(github.event.pull_request.head.ref, 'codex/') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'codex')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.CUSTOM_GH_TOKEN }}   # PAT или токен GitHub App
        fetch-depth: 0

    # подключаем merge-драйверы **до** ребейза
    - name: Register merge drivers
      run: |
        git config --global merge.keep-bot.name "keep bot version"
        git config --global merge.keep-bot.driver "bash -c 'cp %B %A'"
        {
          echo 'README.md           merge=union'
          echo 'index.html          merge=keep-bot'
          echo 'assets/common.js    merge=keep-bot'
        } >> .gitattributes
        git add .gitattributes
        git commit -m "ci: register merge drivers" || true

    - name: Rebase
      uses: cirrus-actions/rebase@v3
