name: Auto‑accept Codex PR

on:
  pull_request_target:
    # Запускается для PR, направленных в основную ветку
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  codex-auto-merge:
    # Работа срабатывает только для веток или PR с пометкой Codex
    if: |
      startsWith(github.event.pull_request.head.ref, 'codex/') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write          # требуется для force‑push и слияния
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}  # PAT с contents:write, pull-requests
          ref:  ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.email "codex@example.com"
          git config user.name "Codex Bot"

      - name: Rebase onto main, предпочитая изменения Codex
        run: |
          git fetch origin main
          # 1) Пытаемся rebase, оставляя версии из ветки Codex при конфликте (-X theirs)
          if ! git rebase -X theirs origin/main ; then
            # 2) Если rebase не удался (редко), откатываемся и делаем merge с приоритетом Codex
            git rebase --abort || true
            git merge -X theirs --no-edit origin/main
          fi
          # Обновляем PR ветку
          git push --force-with-lease

      - name: Merge pull request
        uses: peter-evans/merge-pull-request@v2
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
          merge_method: squash   # или merge/fast-forward — на ваше усмотрение
          delete_branch: true
          commit_title: "codex: auto‑merged by workflow"
          commit_message: "Automatically accepting all changes from Codex."
