# .github/workflows/auto-rebase.yml
name: Auto-rebase Codex PR

on:
  pull_request_target:      # нужны права репозитория
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  rebase:
    if: startsWith(github.event.pull_request.head.ref, 'codex/') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write        # нужно для force-push
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}  # PAT c contents:write, workflow
          ref:  ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Rebase onto main
        uses: peter-evans/rebase@v3
        with:
          base: ${{ github.event.pull_request.base.ref }}   # чаще всего 'main'
          rebase-options: -Xtheirs                         # «бери изменения из PR»

