# .github/workflows/auto-rebase.yml  (должен быть уже в main!!)
name: Auto-rebase Codex PR
on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  auto-rebase:
    if: startsWith(github.event.pull_request.head.ref, 'codex/') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "codex-bot"
          git config user.email "bot@example.com"

      - name: Register merge drivers
        run: |
          git config --global merge.keep-bot.driver "bash -c 'cp %B %A'"
          {
            echo 'README.md merge=union'
            echo 'index.html merge=keep-bot'
            echo 'assets/common.js merge=keep-bot'
          } >> .gitattributes
          git add .gitattributes
          git commit -m 'ci: add merge drivers' || true

      - name: Rebase onto main
        id: rebase
        run: |
          git fetch origin main
          if ! git rebase origin/main -X ours; then
            echo "conflicted=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto-resolve docs
        if: steps.rebase.outputs.conflicted == 'true'
        run: |
          git diff --name-only --diff-filter=U | \
            grep -E '(^README\\.md$|\\.html$)' | \
            xargs -I{} git checkout --theirs {}
          git add -u
          git rebase --continue || git rebase --skip

      - name: Push changes
        if: success()
        run: git push --force-with-lease
