  resolve-doc-conflicts:
    needs: rebase
    if: cancelled() || failure()   # rebase завершился конфликтом
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { token: ${{ secrets.CUSTOM_GH_TOKEN }}, ref: ${{ github.head_ref }} }
      - name: Auto-resolve docs
        run: |
          git diff --name-only --diff-filter=U |
          grep -E '(^README\.md$|\.html$)' |
          xargs -I{} git checkout --theirs {}
          git add -u
          git commit -m "bot: auto-resolve doc conflicts" || true
          git push
