name: Auto-rebase Codex PR
on:
  pull_request_target:
    types: [synchronize, labeled]
    branches: [main]
    paths-ignore: ['**.md']
jobs:
  rebase:
    if: github.actor == 'codex/index-html'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
      - name: Rebase
        uses: cirrus-actions/rebase@v3
