# .github/workflows/auto-rebase.yml  (должен быть уже в main!!)
name: Auto-rebase Codex PR
on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  rebase:
    if: startsWith(github.event.pull_request.head.ref, 'codex/') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
          fetch-depth: 0

      - name: Register merge drivers
        run: |
          git config --global merge.keep-bot.driver "bash -c 'cp %B %A'"
          {
            echo 'README.md merge=union'
            echo 'index.html merge=keep-bot'
            echo 'assets/common.js merge=keep-bot'
          } >> .gitattributes
          git add .gitattributes
          git commit -m 'ci: add merge drivers' || true

      - name: Rebase onto main
        uses: cirrus-actions/rebase@v3
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

  resolve-doc-conflicts:
    needs: rebase
    if: cancelled() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Auto-resolve docs
        run: |
          git diff --name-only --diff-filter=U |
          grep -E '(^README\.md$|\.html$)' |
          xargs -I{} git checkout --theirs {}
          git add -u
          git commit -m "bot: auto-resolve doc conflicts" || true
          git push
      - name: Retry rebase
        uses: cirrus-actions/rebase@v3
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
  auto-merge:
    needs: [rebase, resolve-doc-conflicts]
    if: >-
      (needs.rebase.result == 'success' || needs.resolve-doc-conflicts.result == 'success') &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
          merge-method: squash
